import { reactive } from "vue";

export const store = reactive({
  movieTitle: "",
  apiUriMovies:
    "https://api.themoviedb.org/3/search/movie?api_key=5cf2112ddf23b3b71a19a74fcd05ae67&language=it-IT&query=",
  apiUriTvSeries:
    "https://api.themoviedb.org/3/search/tv?api_key=5cf2112ddf23b3b71a19a74fcd05ae67&language=it-IT&query=",
  resultMovies: [
    {
      backdrop_path: "/hQjCwC222uOusRsAqEOoTHY0sBX.jpg",
      id: 10889,
      language: "en",
      original_title: "Gloria",
      poster_path: "/kfhxjoaHZVNkyVrE9MhkvdENb9V.jpg",
      title: "Gloria - Una notte d'estate",
      vote: 6.839,
    },
    {
      backdrop_path: "/yXuJeoPkxYjWS9XyNzuR8VDZLLJ.jpg",
      id: 264401,
      language: "es",
      original_title: "Gloria",
      poster_path: "/1yVRLamL1TixPSrWAJQ51AI6PZr.jpg",
      title: "Gloria",
      vote: 7.439,
    },
    {
      backdrop_path: "/6rlOgCIxCuJj1cmlPcaBekgQuRb.jpg",
      id: 45712,
      language: "en",
      original_title: "Gloria",
      poster_path: "/1AKAfnT3nm7asU9qyNT6gtS1vbe.jpg",
      title: "Gloria",
      vote: 5.734,
    },
    {
      backdrop_path: "/xqc5l6CCOBqni0gT9J2nvodhCD.jpg",
      id: 160068,
      language: "es",
      original_title: "Gloria",
      poster_path: "/t1copJu3ecVx7zVCBA1o6z02WcZ.jpg",
      title: "Gloria",
      vote: 6.68,
    },
    {
      backdrop_path: "/bIxK8MpVIRTJEK1JtbPXdX7IE4B.jpg",
      id: 245749,
      language: "pt",
      original_title: "Glória",
      poster_path: "/q4tt5JvK8kcrH1tbG2aXLOd6xlo.jpg",
      title: "Gloria",
      vote: 5.8,
    },
    {
      backdrop_path: "/w1EeJYo5X4KtfJ9HNB2sYLa3bHe.jpg",
      id: 686168,
      language: "en",
      original_title: "Gloria",
      poster_path: "/bqygB0yuuS3xizeDxCBD8Iye9js.jpg",
      title: "Gloria",
      vote: 0,
    },
  ],

  resultTvSeries: [
    {
      backdrop_path: null,
      id: 6572,
      language: "en",
      original_title: "Gloria",
      poster_path: "/4E0Posbd16qRwkHQsemgtaKf5nT.jpg",
      title: "Gloria",
      vote: 5,
    },
    {
      backdrop_path: "/rdzzVK4dPlZP1POAtBiotXRKOKz.jpg",
      id: 109369,
      language: "pt",
      original_title: "Glória",
      poster_path: "/aug3brGNuTlo70TyhwJ4XTlnMHC.jpg",
      title: "Glória",
      vote: 6.4,
    },
    {
      backdrop_path: "/spwu5U5PsYUJyWpSJNgD4UBemsN.jpg",
      id: 119881,
      language: "fr",
      original_title: "Gloria",
      poster_path: "/4cqiFPzbhHObt0NGZu3lojKaUgm.jpg",
      title: "Gloria",
      vote: 6.9,
    },
    {
      backdrop_path: null,
      id: 100380,
      language: "en",
      original_title: "Gloria",
      poster_path: "/6GVNNrupFa1CR1Fua22ChU3Icj.jpg",
      title: "Gloria",
      vote: 0,
    },
    {
      backdrop_path: "/9JhtTmFRO3knEzVo3SnuhTDq1Wz.jpg",
      id: 156587,
      language: "en",
      original_title: "Gloria's House",
      poster_path: "/ejpCJLLiF8PJhdzWJiliMIYARG8.jpg",
      title: "A casa di Gloria",
      vote: 0,
    },
    {
      backdrop_path: "/7vCSrzwqS5PEm0i5mHlkDfjHcnX.jpg",
      id: 136283,
      language: "ko",
      original_title: "더 글로리",
      poster_path: "/uUM4LVlPgIrww07OoEKrGWlS1Ej.jpg",
      title: "The Glory",
      vote: 8.573,
    },
  ],
  favourites: [],
  poster: {
    posterUrl: "https://image.tmdb.org/t/p/",
    posterWidth: "w154/",
  },
  newVote: null,
  modal: {
    show: false,
    srcPoster: "",
    scrBackdrop: "",
    title: "",
    originalTitle: "",
    language: "",
    vote: "",
  },
  showMovies: true,
  showTvSeries: true,
});
